package ua.vg.vp.util;

public enum EventType {
    UA_STATE,INCOMING_CALL,PEER_CONNECTION,ADD_STREAM,CALLING,ANSWERED,CONNECTION,CONFIRMED,ENDED,USER_MEDIA_FAILED,FAILED,IDLE,AUDIO_MUTED,AUDIO_UN_MUTED,HOLD,UN_HOLD,VIDEO_MUTED,VIDEO_UN_MUTED,GET_USER_MEDIA
}
